name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo '${{ secrets.FIREBASE_CREDENTIALS_JSON }}' | sudo tee /home/ec2-user/Smart_agro_backend_laravel_new/storage/firebase-credentials.json > /dev/null
            sudo chown 33:33 /home/ec2-user/Smart_agro_backend_laravel_new/storage/firebase-credentials.json
            cd ~/Smart_agro_backend_laravel_new
            ./deploy.sh
